# Generated by Django 4.2.14 on 2024-07-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LibreDeAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('fecha_fabricacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=1000)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='alimentos/')),
                ('cantidad', models.PositiveIntegerField()),
                ('proteinas', models.FloatField(max_length=3, null=True)),
                ('carbohidratos', models.FloatField(max_length=3, null=True)),
                ('grasas', models.FloatField(max_length=3, null=True)),
                ('energia', models.FloatField(max_length=3, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoriaalimento')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoLibreDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alimento')),
                ('id_libre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libredealimento')),
            ],
            options={
                'unique_together': {('alimento', 'id_libre')},
            },
        ),
        migrations.CreateModel(
            name='AlimentoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alimento')),
                ('id_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dieta')),
            ],
            options={
                'unique_together': {('alimento', 'id_dieta')},
            },
        ),
    ]
