# Generated by Django 4.2.14 on 2024-07-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
