# Generated by Django 4.2.14 on 2024-07-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
        ('app', '0004_pedido_remove_carrito_creado_en_pedidoitem'),
    ]

    operations = [
    ]
